export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const SET_USER = "SET_USER";
export const RESET = "RESET";
//----------------------------------Authentication---------------------------------------//
//Send OTP
export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAILURE = "SEND_OTP_FAILURE";

//Verity OTP
export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const CLEAR_AUTH = 'CLEAR_AUTH';

//-----------------------------------CHAT-------------------------------------------------//

//POST= Ask 
export const POST_ASK_REQUEST = "POST_ASK_REQUEST";
export const POST_ASK_SUCCESS = "POST_ASK_SUCCESS";
export const POST_ASK_FAILURE = "POST_ASK_FAILURE";

// POST = NEW CHAT
export const POST_NEW_CHAT_REQUEST = "POST_NEW_CHAT_REQUEST";
export const POST_NEW_CHAT_SUCCESS = "POST_NEW_CHAT_SUCCESS";
export const POST_NEW_CHAT_FAILURE = "POST_NEW_CHAT_FAILURE";

//GET = GET USER ALL CHAT
export const GET_USER_ALL_CHAT_REQUEST = "GET_USER_ALL_CHAT_REQUEST";
export const GET_USER_ALL_CHAT_SUCCESS = "GET_USER_ALL_CHAT_SUCCESS";
export const GET_USER_ALL_CHAT_FAILURE = "GET_USER_ALL_CHAT_FAILURE";
export const CHAT_CLEAR = "CHAT_CLEAR";

//POST=LOAD CHAT 
export const POST_LOAD_CHAT_REQUEST = "POST_LOAD_CHAT_REQUEST";
export const POST_LOAD_CHAT_SUCCESS = "POST_LOAD_CHAT_SUCCESS";
export const POST_LOAD_CHAT_FAILURE = "POST_LOAD_CHAT_FAILURE";

// APPEND = Add new message locally
export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT";
export const APPEND_CHAT_MESSAGE = "APPEND_CHAT_MESSAGE";
export const MOVE_CHAT_TO_TOP = "MOVE_CHAT_TO_TOP";
export const UPDATE_CHAT_TITLE_LOCAL = "UPDATE_CHAT_TITLE_LOCAL";
export const ADD_NEW_CHAT_TO_LIST = "ADD_NEW_CHAT_TO_LIST";

//GET= SINGLE USER CHAT
export const GET_USER_CHAT_REQUEST = "GET_USER_CHAT_REQUEST";
export const GET_USER_CHAT_SUCCESS = "GET_USER_CHAT_SUCCESS";
export const GET_USER_CHAT_FAILURE = "GET_USER_CHAT_FAILURE";

//PUT= UPDATE CHAT TITLE
export const PUT_CHAT_TITLE_REQUEST="PUT_CHAT_TITLE_REQUEST";
export const PUT_CHAT_TITLE_SUCCESS="PUT_CHAT_TITLE_SUCCESS";
export const PUT_CHAT_TITLE_FAILURE="PUT_CHAT_TITLE_FAILURE";

//DELETE =DELETE CHAT SESSION endpoint
export const DELETE_CHAT_REQUEST="DELETE_CHAT_REQUEST";
export const DELETE_CHAT_SUCCESS="DELETE_CHAT_SUCCESS";
export const DELETE_CHAT_FAILURE="DELETE_CHAT_FAILURE";

// POST=SEARCH CHAT 
export const POST_SEARCH_CHAT_REQUEST = "POST_SEARCH_CHAT_REQUEST";
export const POST_SEARCH_CHAT_SUCCESS = "POST_SEARCH_CHAT_SUCCESS";
export const POST_SEARCH_CHAT_FAILURE = "POST_SEARCH_CHAT_FAILURE";

//POST =ARCHIVE CHAT 
export const POST_ARCHIVE_CHAT_REQUEST = "POST_ARCHIVE_CHAT_REQUEST";
export const POST_ARCHIVE_CHAT_SUCCESS = "POST_ARCHIVE_CHAT_SUCCESS";
export const POST_ARCHIVE_CHAT_FAILURE = "POST_ARCHIVE_CHAT_FAILURE";

//POST=CONTINUE CHATBOT
export const POST_CHATBOT_CONTINUE_REQUEST = "POST_CHATBOT_CONTINUE_REQUEST";
export const POST_CHATBOT_CONTINUE_SUCCESS = "POST_CHATBOT_CONTINUE_SUCCESS";
export const POST_CHATBOT_CONTINUE_FAILURE = "POST_CHATBOT_CONTINUE_FAILURE";

// POST= GET CHAT HISTORY
export const POST_CHAT_HISTORY_REQUEST = "POST_CHAT_HISTORY_REQUEST";
export const POST_CHAT_HISTORY_SUCCESS = "POST_CHAT_HISTORY_SUCCESS";
export const POST_CHAT_HISTORY_FAILURE = "POST_CHAT_HISTORY_FAILURE";

//-----------------------------------USER PROFILE-------------------------------------------------//

// GET = USER PROFILE
export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

//PATCH = Update User Profile Patch
export const PATCH_USER_PROFILE_REQUEST = "PATCH_USER_PROFILE_REQUEST";
export const PATCH_USER_PROFILE_SUCCESS = "PATCH_USER_PROFILE_SUCCESS";
export const PATCH_USER_PROFILE_FAILURE = "PATCH_USER_PROFILE_FAILURE";

// RESET = Reset Update Success State
export const RESET_UPDATE_SUCCESS = "RESET_UPDATE_SUCCESS";

// POST = Update User Profile With Picture
export const POST_USER_PROFILE_REQUEST = "POST_USER_PROFILE_REQUEST";
export const POST_USER_PROFILE_SUCCESS = "POST_USER_PROFILE_SUCCESS";
export const POST_USER_PROFILE_FAILURE = "POST_USER_PROFILE_FAILURE";

//DELETE= Delete user Account
export const DELETE_ACCOUNT_REQUEST="DELETE_ACCOUNT_REQUEST";
export const DELETE_ACCOUNT_SUCCESS="DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAILURE="DELETE_ACCOUNT_FAILURE";